import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Petition from "../components/petition";
import Test from "../components/test";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>DocsLaw</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <nav className="navbar navbar-light bg-light p-2">
          <h3>Docs-Law Demo</h3>
        </nav>

        <Petition />
      </main>
    </>
  );
}
